# Generated by Django 2.1.4 on 2019-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='rank',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
